# fly.toml app configuration file
app = "django-demo-app"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  DEBUG = "False"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512